module: SparkDigital
author: Carlos Duclos
github_url: https://github.com/carlos21/spark-digital-demo

theme: fullwidth
clean: true
# exclude: [SparkDigital/**]
# include: [PresentationLogic/**]

# readme: README.md

skip_undocumented: true
hide_documentation_coverage: false

xcodebuild_arguments: [-workspace, SparkDigital.xcworkspace, -scheme, SparkDigital]

# jazzy \
#   --module Core \
#   --output docs/core \
#   --min-acl private \
#   --min-acl internal

# jazzy \
#   --module SparkDigital \
#   --output docs/presentation \
#   --min-acl private \
#   --min-acl internal
